### PR TITLE
bump ndpack-image to 3.x

### LINKED ISSUE #2: this library can't be installed via lerna
because of this dep tree

```
└─┬ baboon-image@2.0.0
  └─┬ ndpack-image@2.0.0
    └─┬ save-pixels@1.0.0
      └── pngjs@0.4.0
```

and results of `error pngjs@0.4.0: The engine "node" is incompatible with this module. Expected version "0.8.x".`

any reason to stay on ndpack-image 2.x ?

can it be upgraded to 3.x ? thanks

### PR DESCRIPTION
**Pull request by gre**
fixes https://github.com/scijs/baboon-image/issues/2

### CODE REVIEW

**Comment by rreusser** [comment]
I'm glad to make this change. I'll test it out quickly first tomorrow. [get-pixels](https://github.com/scijs/get-pixels/commits/master) has changed quite a bit, seems. Pinging @mikolalysenko just in case he knows of any problems, otherwise the deciding factor is just an actual once over to verify that it works. It wouldn't be the first time I've upgraded a dependency and broken something obscure in the process so just want to double check.

**Comment by rreusser** [comment]
@gre I added a trivial test just to be sure and merged this PR. Working through the get-pixels [commit history](https://github.com/scijs/get-pixels/commits/master), is a minor version increment is appropriate? Seems like a patch, but I suppose it's not inconceivable a major pngjs upgrade could cause issues.

**Comment by gre** [comment]
yeah I think minor might be fine. (but obviously not a patch ;) )

**Comment by gre** [comment]
thanks for taking time of this :)

**Comment by rreusser** [comment]
Just to nitpick since I struggle with this, is there a strictly correct answer? Nothing about the function of this module has changed, but the compatibility of its dependencies perhaps does. So not a patch. Maybe a minor. Major is perhaps going too far?

**Comment by gre** [comment]
yeah, to be honest i was not sure.
but then I search a bit on semver.org and they mention this here: http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

> **What should I do if I update my own dependencies without changing the public API?**
>
> That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality. I would usually expect additional code for the latter instance, in which case it’s obviously a minor level increment.

so if I understand correctly it might even be fine to bump a patch? Somehow I feel a minor is safer in that it will not just break your deps dedup..

**Comment by rreusser** [comment]
Thanks for the link! Maybe I'll go with minor just in case. None of this probably even matters for this particular library, but I'm really trying to improve the quality/rigor of what I write these days……

Thanks so much for the PR/feedback!

Published v2.1.0

**Pull request merged**
